lean/main.go

`lean xxx` 转为调用当前环境变量中的 `lean-xxx` 命令。

feat: allow third party command

---

lean/api/client.go
lean/api/file.go
lean/boilerplate/boilerplate.go
lean/check_update.go
lean/deploy_action.go
lean/glide.lock
lean/glide.yaml
lean/info_action.go
lean/main.go
lean/up_action.go
lean/vendor/github.com/cheggaaa/pb/.travis.yml
lean/vendor/github.com/cheggaaa/pb/LICENSE
lean/vendor/github.com/cheggaaa/pb/README.md
lean/vendor/github.com/cheggaaa/pb/format.go
lean/vendor/github.com/cheggaaa/pb/pb.go
lean/vendor/github.com/cheggaaa/pb/pb_appengine.go
lean/vendor/github.com/cheggaaa/pb/pb_nix.go
lean/vendor/github.com/cheggaaa/pb/pb_solaris.go
lean/vendor/github.com/cheggaaa/pb/pb_win.go
lean/vendor/github.com/cheggaaa/pb/pb_x.go
lean/vendor/github.com/cheggaaa/pb/pool.go
lean/vendor/github.com/cheggaaa/pb/pool_win.go
lean/vendor/github.com/cheggaaa/pb/pool_x.go
lean/vendor/github.com/cheggaaa/pb/reader.go
lean/vendor/github.com/cheggaaa/pb/runecount.go
lean/vendor/github.com/cheggaaa/pb/termios_bsd.go
lean/vendor/github.com/cheggaaa/pb/termios_nix.go
lean/version/version.go

文件上传／下载相关改动

---

lean/api/cookies.go
lean/console/runtime.go
lean/utils/home.go

使用 XDG config dir

---

lean/apps/app.go

feat: support legency project config

---

lean/api/file.go
lean/main.go
lean/upload_action.go

feat: support upload command

---

lean/api/account.go
lean/api/client.go
lean/login_action.go

fead: login us region server while login

---

lean/api/account.go
lean/api/app_router.go
lean/api/apps.go
lean/api/client.go
lean/api/cookies.go
lean/api/event_poller.go
lean/api/file.go
lean/api/regions/regions.go
lean/check_out_action.go
lean/deploy_action.go
lean/init_action.go
lean/upload_action.go

feat: support app router, and support us region

---

Makefile
lean/api/apps.go
lean/apps/app.go
lean/apps/recent.go
lean/apps/recent_test.go
lean/check_out_action.go
lean/deploy_action.go

安最近关联应用顺序，动态调节 `lean checkout` 的列表顺序

feat: order apps while `lean checkout` using lastest linked order

---

lean/deploy_action.go
lean/error.go
lean/runtimes/runtime.go

fix: check error returned by runtimes.Detect

---

lean/runtimes/runtime.go
lean/up_action.go

feat: show upgrade document when detected cloudcode 2.0 runtime

---

lean/up_action.go

fix: slice assgin

---

Makefile
lean/api/cookies.go
lean/main.go
lean/stats/collect.go
lean/stats/deviceid.go
lean/stats/deviceid_test.go

feat: add basic stats feature

---

lean/api/leancache.go
lean/cache_action.go
lean/cache_list.go
lean/main.go

feat: support leancache commands

---

lean/api/account.go
lean/api/client.go
lean/api/error.go
lean/api/file.go

fix: better error handling while got HTML content in api function call

---

lean/api/apps.go
lean/deploy_action.go
lean/main.go

fead: allow `--message` param in deploy command

---

lean/api/event_poller.go
lean/api/log.go

fix: retry while got error in fetch log actions

---

lean/boilerplate/boilerplate.go

fix: invalid file permission in init boilerplate

---

lean/api/cql.go
lean/cache_action.go
lean/cql_action.go
lean/main.go

feat: add CQL subcommand

---

lean/apps/app.go
lean/runtimes/runtime.go

fix: bugfix in node runtime detect

---

lean/deploy_action.go
lean/main.go
lean/runtimes/ignorefiles.go
lean/runtimes/runtime.go

github.com/jhoonb/archivex 这个库不能向 zip 包添加一个文件时重命名这个文件（zip 包中的 war 文件需要是 `ROOT.war`），所以自己实现了这部分逻辑。

feat: deploy WAR package for Java runtime

---

lean/console/index_html.go
lean/console/server.go

fix: invalid hook sign and missing user object in hook call

---

lean/api/apps.go
lean/deploy_action.go
lean/main.go

feat: allow --no-cache option in deploy subcommand

---

lean/console/server.go
lean/init_action.go

https://github.com/ahmetalpbalkan/go-linq/issues/42
https://github.com/ahmetalpbalkan/go-linq/issues/43

fix: hack the bugs caused by go-linq

---

lean/api/apps.go
lean/env_action.go
lean/up_action.go

feat: export LEANCLOUD_APP_HOOK_KEY to env while `lean up` / `lean env`

---

lean/api/apps.go
lean/deploy_action.go
lean/main.go

feat: support --revision option in deploy subcommand

---

lean/up_action.go

feat: disable buggy --watch option in up subcommand

---

lean/check_out_action.go
lean/main.go

允许 `lean checkout app-name`，并且不管是 checkout app-name 还是 app-id，都会从服务器检查正确性。
close: #176

feat: allow checkout app name

---

lean/console/server.go
lean/up_action.go

https://github.com/leancloud/lean-cli/issues/199

fix: don't crash while there is a cloud function named ""

---

lean/runtimes/runtime.go

fix: skip dir if it matches the ignore rules

---

lean/check_out_action.go
lean/logs_action.go

feat: show current app while checout app

---

lean/deploy_action.go
lean/runtimes/ignorefiles.go
lean/runtimes/runtime.go

feat: refactor deploy codes, and don't detect runtime while deploy war file

---

lean/info_action.go

fix: invalid region in info command

---

commands/up_action.go

feat: show current app's name while using up command

---

commands/up_action.go

:bug: fix console and runtime log conflicts

---

commands/app.go
commands/switch_action.go

:boom: change `checkout` command to `switch`

---

commands/app.go
commands/deploy_action.go

https://github.com/leancloud/docs/issues/1939

:bug: remove checkout command help

---

runtimes/runtime.go

:checkered_flag: fix python runtime search path on windows

---

commands/env_action.go

:bug: remove console output in env command

---

runtimes/runtime.go

close: https://github.com/leancloud/lean-cli/issues/261

:boom: show a warning on lean up while using leanengine sdk version less than 1.0.0

---

api/event_poller.go
commands/deploy_action.go
commands/publish_action.go

:lipstick: show app info while deploy

---

runtimes/runtime.go
utils/bom.go

:hankey: support UTF-8 BOM header for package.json file

---

commands/switch_action.go

:bug: fix invalid project group config after switch app using appName / appID

---

api/log.go
commands/app.go
commands/logs_action.go
utils/api.go

需要等待 https://github.com/leancloud/cloud-code/issues/1271 解决之后才可以 merge。

:sparkles: support from / to params in log command

---

misc/lean-bash-completion
misc/lean-zsh-completion

https://github.com/leancloud/lean-cli/issues/180

:sparkles: add bash complete support

---

boilerplate/boilerplate.go

```
[INFO] 下载模版文件 23.55 KiB / 23.55 KiB [=========================] 100.00% 0s
[INFO] 正在创建项目...
[INFO] 创建 Koa 项目成功，更多关于 Koa 的文档请参考官网： http://koajs.com/
```

:lipstick: show web framework's homepage after init

---

commands/env_action.go
commands/up_action.go

:sparkles: add `LEAN_CLI_HAVE_STAGING` enviroment variable

---

.gitignore
commands/third_party_command.go

自动先检查 `$PROJECT-DIR/bin` 下有没有可执行的文件，然后再在系统 PATH 搜索。
需不需要将 `bin` 换一个名称，例如：`lean-bin`？

Enhencement in issue #273

---

api/apps.go
commands/env_action.go
commands/up_action.go

:sparkles: add LEANCLOUD_APP_DOMAIN environment varialble

---

api/account.go
api/regions/regions.go
commands/login_action.go

:alien: login TAB region with username and password

---

api/account.go
api/client.go

:sparkles: support 2fa

---

glide.lock
vendor/github.com/aisk/wizard/wizard.go

修改了 init 时选项文字的颜色，之前蓝色在 windows 的 cmd.exe 默认配置下，很难和背景颜色区分出来。

:arrow_up: update wizard

---

README.md
api/apps.go
boilerplate/boilerplate.go
commands/app.go
commands/deploy_action.go
commands/init_action.go
commands/publish_action.go
packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
version/version.go

https://github.com/leancloud/lean-cli/issues/110
https://github.com/leancloud/cloud-code/issues/1211
https://github.com/leancloud/cloud-code/issues/1340

使用 commit message 作为备注、init 时允许指定目录等

---

api/log.go
api/metric.go
commands/logs_action.go
commands/metric_action.go
vendor/github.com/go-yaml/yaml/emitterc.go
vendor/github.com/go-yaml/yaml/example_embedded_test.go

LeanCloud 存储->API 请求数 的接口中，会忽略零请求的天数。
原先代码会导致 RuntimeError，修复后能正常使用。

:bug: fix bug in api.FetchReqStat

---

apps/region_cache.go
commands/info_action.go
commands/login_action.go
commands/switch_action.go
packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
version/version.go

https://leanticket.cn/tickets/16031

🐛 Fix login

---

api/account.go
api/file.go
commands/app.go
commands/deploy_action.go
commands/init_action.go
commands/login_action.go

https://github.com/leancloud/lean-cli/issues/402
https://github.com/leancloud/lean-cli/issues/401
服务器还没上线，暂时还无法测试

🌐 Ask region when login; Login to us region directly; Upload to s3 in us region

---

console/resources/index.html

cdn.staticfile.org is not actively maintained.

🐛Migrate console resources to cdn.jsdelivr.net

---

commands/app.go

:speech_balloon: redirect `help cmd` to `cmd -h`

---

api/client.go

fix: fallback default locale to en_US.UTF-8

---

commands/cache_action.go

https://www.leanticket.cn/tickets/36800

🐛 Fix cache select

---

lean/check_update.go

fix: print update notice to stderr instead of stdout

---

api/client.go

👽 Change dashboard urls

---

commands/action_warpper.go

Thus the error message "User doesn't sign in." becomes more friendly to users with applications at multi regions.
Thank YuGao for bringing this to our attention (ticket 37295).

chore: include region info on not sign in error msg

---

Makefile

https://github.com/Homebrew/homebrew-core/blob/master/Formula/lean-cli.rb
Homebrew 应该是早就有 arm 版了。

🎉 Build for Apple Silicon

---

commands/deploy_action.go
commands/switch_action.go

- `lean deploy` 在部署前通过 `Deployable`  检查是否有可以部署的实例
- `lean switch` 增加 region 显示 -> `Switching to yqiu-test (region: cn-n1, group: web)`

check deployable before deploy and add groupName in lean switch output

---

runtimes/runtime.go

fix https://github.com/leancloud/spring-boot-getting-started/issues/1
<sub>Credits to GitHub Copilot</sub>

run spring-boot projects with `mvn spring-boot:run`

---

commands/deploy_action.go
packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
packaging/msi/tds-cli-x64.wxs
packaging/msi/tds-cli-x86.wxs
version/version.go

To support specifying `startupTimeout`, `functionsMode` and Java version.

upload additional leanengine.yaml and system.properties files with ROOT.war

---

runtimes/ignorefiles.go
runtimes/runtime.go

✨ Follow up the static runtime

---

lean/main.go

fix: ignore if update check fails

---

api/app_router.go
api/regions/regions.go
commands/app.go
commands/login_action.go

https://git.gametaptap.com/tds/LeanCloud/Backend/cloud-engine/-/issues/1926

🔥 Remove app-router, use shared domains

---

boilerplate/boilerplate.go
commands/new_action.go

- 先选模板再选应用
- 模板列表的格式从 `Express - Node.js` 改成 `Node.js - Express` 这样看上去更整齐
使用 npx 创建 React 或 Vue 的模板和需要的 `leanengine.yaml`、`static.json` 这两个文件，效果大概是：
```
❯ lean new vue2                                                                                                                                                                                                                                                      
[?] Please select an app template:
1) Node.js - Express
2) Node.js - Koa
3) Python - Flask
4) Python - Django
5) Java - Serlvet
6) Java - Spring Boot
7) PHP - Slim
8) .NET Core
9) Go - Echo
10) React Web App (via create-react-app)
11) Vue Web App (via @vue/cli)
=> 11
[?] Please select an app:
1) test
=> 1
[INFO] Executing `npx @vue/cli create --default --packageManager npm vue2` …
```

✨ Create React or Vue project via lean new

---

commands/env_action.go
commands/up_action.go

给 `lean env` 和 `lean up` 添加 `LEANCLOUD_APP_GROUP` 环境变量。

add LEANCLOUD_APP_GROUP environment variable

---

packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
packaging/msi/tds-cli-x64.wxs
packaging/msi/tds-cli-x86.wxs
version/version.go

- Provide `LEANCLOUD_APP_GROUP` environment variable when using `lean up` or `lean env`.
- Internal HTTP API changes.

🔖 Release 1.1.0

---

commands/up_action.go
runtimes/runtime.go

Support running https://github.com/leancloud/servlet-getting-started/tree/gradle with `lean up`.

Lean up gradle

---

api/domain_center.go
api/engine.go
commands/app.go
commands/deploy_action.go
commands/preview_action.go
commands/publish_action.go
go.mod
go.sum
packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
packaging/msi/tds-cli-x64.wxs
packaging/msi/tds-cli-x86.wxs
version/version.go

用 `lean preview deploy` 来部署预览环境，预期是在 CI 中运行，会自动读取 PR 号、commit 等环境变量；也可手动指定：`lean preview deploy --name pr-123 --commit 93f1f76a8de63d5d6b526ec19a6b93fd5b59bc77 --url https://github.com/leancloud/lean-cli/pull/519`。

Preview environments

---

commands/preview_action.go
packaging/deb/control-x64
packaging/deb/control-x86
packaging/msi/lean-cli-x64.wxs
packaging/msi/lean-cli-x86.wxs
packaging/msi/tds-cli-x64.wxs
packaging/msi/tds-cli-x86.wxs
version/version.go

https://github.com/orgs/community/discussions/26325

Fix GITHUB_SHA is not correct in pull request triggered jobs

---

commands/app.go
commands/preview_action.go

Add more options from `lean deploy` to `lean preview deploy`.

Add --direct and --options to `lean preview deploy`

---

commands/deploy_action.go
commands/preview_action.go

Use `--direct=true/false` to explicitly set if first upload project to file class.

Use direct upload in US region
