leancloud/lean-cli

lean/check_update.go, lean/deploy_action.go, lean/main.go, lean/publish_action.go
使用 `brew install lean-cli --HEAD` 方式安装命令的用户，不自动检查更新。
=> homebrew HEAD 安装的二进制不检查更新

lean/api/apps.go, lean/api/event_poller.go
命令行工具用到的这几个 API 应该都已经上线了，本地测试没有问题。API 地址调整的详情在 https://github.com/leancloud/cloud-code/pull/995 里有描述。
=> Update leanengine api endpoint prefix to /1.1/engine

lean/api/event_poller.go, lean/main.go
=> fix: don't show `deploy failed` when last deploy log's level is not error

lean/check_out_action.go
because the merge function is buggy with multi regions
=> fix: disable app merge when checkout app

lean/api/app_router.go, lean/api/apps.go, lean/info_action.go
之前都是统一通过 https://app-router.leancloud.cn/1/route?appId=xxx 来判断节点信息的，后来实际上美国节点的应用信息并不能在 app router 上查询到（但是带 - 后缀的可以查询），导致有一批美国节点的应用部署的时候会出现问题。
这个 PR 在根据节点获取应用列表的时候会把列表中所以应用的 app router 信息保存到磁盘，就不必担心此问题了。
=> feat: persistence app router cache

lean/check_out_action.go
不确定是不是 go-linq 的 bug，按原来的代码执行结果会让 appList 出现重复数据。暂时先绕过了。
=> fix: duplicated checked out apps

lean/console/index_html.go
方便将测试环境部署在自己内网服务器上。
避免内网其他机器访问内网服务器测试云代码的时候报错。
=> 避免出现远程调试测试环境出错的情况

lean/runtimes/runtime.go
=> fix: ignore file dose not work on Windows

commands/app.go, commands/third_party_command.go
现在执行 `$ lean xxxxxxx` ，会在 `$PATH` 中寻找 `lean-xxxxxxx` 的可执行文件，如果找到，自动执行此命令。
并且如果当前目录是个 LeanEngine 项目目录，在 `lean-xxxxxxx` 进程的环境变量中，可以获得 `$LEANCLOUD_APP_ID` 等环境变量。
=> :sparkles: support third party command

Makefile, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs
顺便把编译结果改成 `x86` / `x64` 了，防止有的用户以为 `amd64` 只能在 amd 的机器上用。
=> :hammer: refactor makefile

api/client.go, api/log.go, commands/logs_action.go, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, version/version.go
- 对于给 `lean logs` 传入的时间使用本地时区进行解析（之前是使用 UTC 解析）
- 修复 ReceiveLogsByRange 解析日志的顺序：当指定了 `ascend: true`，结果应该是顺序排列的
- 对于非当天日志，打印时带上日期
- 修复将所有 401 认为是需要两步认证的问题（现在会检查 token 字段是否为空）
=> 🌐 Fix `lean logs`

commands/deploy_action.go, commands/up_action.go, runtimes/ignorefiles.go, runtimes/runtime.go
- 修复了 Runtime 中的 Envs 中的环境变量没有实际被加载（而是在 up_action 中被覆盖）的问题
- 遇到不认识的目录结构会打印警告并继续部署
编译好的 macOS 版本： https://lc-kTzCvF3a.cn-n1.lcfile.com/e0a2b1a5d14591d83c06
=> ✨ Support dotnet

lean/main.go, stats/collect.go
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide
逻辑和指标没有改动，只是改成了发到 Google Analytics。
=> 📈 Move to Google Analytics

commands/app.go
Due to the doc site switch to algolia,
the search command does not work.
Consindering that this command is not commonly used,
and [rewrite search command for algolia][413]
will introduce a lot of dependencies (algolia sdk),
this commit removes search command.
[413]: https://github.com/leancloud/lean-cli/pull/413
=> :fire: remove search command

api/engine.go, commands/switch_action.go, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, version/version.go
https://github.com/leancloud/lean-cli/compare/v0.20.1...deployable
Changelog:
- 🔥 Remove `search` command.
- 💥 Remove `--atomic` and `--build-root` options for `deploy` command, you can use `--options` instead, like `lean deploy --options 'buildRoot=backend'`.
- 💥 `lean switch` will not display undeployable group.
- ✨ Add `--prod` for `deploy` command.
- ✨ `lean up` now working for [static](https://github.com/leancloud/static-getting-started) runtime.
- 🐛 `lean deploy` now deploy to staging for Client Engine as expected.
- Internal HTTP API changes.
=>  🔖 Release 0.21.0

api/client.go
Previously, getSystemLanguage directly throws error message
of jibber_jabber.DetectLanguage(),
which is typically "Could not detect Language"
on systems with misconfigured locale.
This may confuse users that lean-cli cannot detect
runtime (programming) language correctly.
This commit added a prefix ("unsupported locale setting")
to the error message.
related issue: #426
related ticket: 20742
=> docs: getSystemLanguage: friendlier locale error

runtimes/runtime.go
1. Do not detect `leanengine.yaml` (intended to be used on cloud).
2. Do not detect `runtime.txt` (outdated, unsupported by cloud now).
3. Defaults to `python` instead of `python2.7` (EOL of py is coming).
=> feat: simplify local python version detection

packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, version/version.go
- (Python) No longer use `cmd` from `leanengine.yaml` (used on cloud only).
- (Python) No longer detect python version  from `runtime.txt` (use `.python-version` instead).
- (Python) Use `python` instead of `python2.7` by default.
- Error message and docs improvements.
- Internal HTTP API changes (Move to new logs API).
[lean-macos-x64.zip](https://github.com/leancloud/lean-cli/files/4817898/lean-macos-x64.zip)
=> 🔖 Release 0.22.0

api/leancache.go, commands/app.go, commands/cache_action.go, commands/cache_list_action.go
https://github.com/leancloud/cloud-code/issues/1700
1. 在 api/leancache.go 中增加了 LeanDB 接口实现
2. 复制 commands/cache_action.go 的 cacheAction 流程，根据 /1.1/leandb/apps/{appId}/clusters 返回结果确定版本分支流程，一支走 LeanCache 流程；一支走 LeanDB 流程（目前流程一致）
3. commands/cache_list_action.go 与 commands/cache_action.go 修改逻辑一致
手动测试 
- lean cache
- lean cache --name=xx --eval=ping
=> Lean cache 支持 LeanDB

packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, version/version.go
- `lean logs` supports UTC timestamp in addition to YYYY-MM-DD.
- `lean cache` Use db0 by default, use `--db <index>` to use other db.
- Allow users to disable GA via an env var(`NO_ANALYTICS`).
- Fix meaningless error message during deploy(`exit status 128`)
- Internal HTTP API changes(related to LeanCache).
- Internal dependency and testing improvements.
[lean-macos-x64.zip](https://github.com/leancloud/lean-cli/files/5033468/lean-macos-x64.zip)
[lean-windows-x64.exe.zip](https://github.com/leancloud/lean-cli/files/5033470/lean-windows-x64.exe.zip)
=> 🔖 Release 0.23.0

api/engine.go, commands/app.go, commands/deploy_action.go, commands/publish_action.go, version/version.go
Support `overwrite-functions` param for `deploy` and `publish` command.
Link issue: #451
=> feat: support overwrite-functions param for deploy and publish command

Makefile, api/client.go, api/regions/regions.go, commands/info_action.go, commands/init_action.go, commands/switch_action.go, console/server.go, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, version/version.go
- Built for TDS, support new `cn-tds1` region.
- Support login by Access Token (can be generated from dashboard), use `--token` to specify access token or `--use-token` for interactive input.
- Support direct upload (`lean deploy --direct`).
- HTTP request debug output `DEBUG=lean lean deploy`.
- Fix debug console for .Net apps.
=> 🔖 Prepare 0.25

Makefile, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, packaging/msi/tds-cli-x64.wxs, packaging/msi/tds-cli-x86.wxs, version/version.go
- Fix Debian deb package for tds-cli.
- Fix `LEANCLOUD_API_SERVER` for tds1 region.
- Embed debug console resources into lean-cli binary.
=> 🔖 Release 0.25.1

commands/app.go
将 `lean upload` 改为 `lean file upload`，避免和 `lean deploy` 混淆。另外方便以后添加下载、删除文件等功能。
=> move `lean upload` to `lean file upload`

Makefile, api/engine.go, api/regions/regions.go, boilerplate/boilerplate.go, commands/app.go, commands/deploy_action.go, commands/publish_action.go, version/version.go
- 三处措辞修改
- 将 `lean deploy --options 'printBuildLogs=true'` 改为更简单的 `lean deploy --build-logs`
- `lean init` 选择 region 时的顺序时常变化，修改为固定的顺序以方便快速选择
- 用命令的名字（`os.Args[0]`）来区分 `lean` 和 `tds`，方便 tds 加入 Homebrew（符号链接到 lean 即可）
=> Prepare 1.0

commands/app.go, commands/init_action.go
- `lean init` 会创建文件夹，这和 `git init` 等命令的行为不同，改为 `lean new`
- 创建的项目名字是 App 名字，如果文件夹已经存在或者 App 名字是中文不太方便，改为必须指定项目名字
closes #475
=> rename `lean init` to `lean new` and make directory name required

api/app_router.go, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, packaging/msi/tds-cli-x64.wxs, packaging/msi/tds-cli-x86.wxs, version/version.go
一个临时改动，之后再改成从 Domain Center 拉取自定义域名，因此这次也只改华北，避免引入新问题。
已检查过修改这里同时对 filesToken（lean deploy 时）和 lean up 有效。
=> 🚑 Replace unavailable lncld.net

commands/app.go, commands/deploy_action.go, lean/main.go
`lean deploy` 在不同付费方案下有着不同的行为，容易让用户困惑。这次调整后：
* 使用 `lean deploy --prod` 来部署生产环境
* 使用 `lean deploy --staging` 来部署预备环境
* `lean deploy` 会交互询问用户环境
* `lean deploy --prod 0|1` 仍然兼容
=> 移除 `lean deploy` 的默认环境，改为需要显式指定

commands/app.go, commands/up_action.go
默认不拉取线上环境变量。
去掉了 --watch 相关的警告，应该在 5 年前就已经去掉相关功能了，几乎没有用户用到。
=> 💥 No longer fetch envs by default

api/client.go, commands/debug_action.go, commands/deploy_action.go, commands/publish_action.go, commands/up_action.go, version/version.go
- 去掉了似乎没什么意义的 `Could not detect Language` 打印
- 在版本信息中加入当前操作系统、架构、binary 名字
- 在 deploy 和 publish 里把部署目标拆成了两行（因为有 appName、appId、group、prod、region 这么多变量，一行很难写明白），其中的变量用绿色突出显示
- 去掉了对用户意义不大的 `Retrieving app info`（但这可能导致用户网络差的时候不知道 lean-cli 卡在哪里）、`Deleting temporary files` 打印
最后效果：
=> 💄 Improve output of deploy and publish

commands/app.go, commands/env_action.go, go.mod, go.sum, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, packaging/msi/tds-cli-x64.wxs, packaging/msi/tds-cli-x86.wxs, version/version.go
fixes #508 
- 用 https://github.com/alessio/shellescape 来转义
- 输出模版由 `{{` 改为 `{{{` 来关闭 HTML 转义 `'` https://github.com/cbroglie/mustache#escaping
- Windows 不用转义，因为 `SET name=v a l` 中等号后面全部都视为值
另外 shellescape 的实现也很有意思，它有一个白名单 `\w@%+=:,./-`，如果输入都在白名单内不做任何操作。如果出现了白名单外的字符，会在输入前后加单引号 `'`，因为 bash 中单引号字符串就是最纯粹的字符串，不会有插值之类的操作。唯一的问题就是如果输入本来就包含单引号会造成不匹配，而且无法通过用其他编程语言中常见的 `\'` 来表示，因为 bash 中 [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) 需要用 `$''` 字符串才行。shellescape 中是利用了 C 系语言中字符串的一个特性：相邻的字面量字符串会自动拼接在一起：
```bash
$ echo 'a''b'
ab
```
它会将原来存在的单引号 `'` 替换成 `'"'"'` （单双单双单）。两边的单引号用来配对之前对前后添加的单引号，中间是双引号中间的单引号 `"'"`，也就是长度为一的字符串。综上，原字符串 `a'b` 会变成三个字符串 `'a' "'" 'b'`（添加了空格帮助阅读）。
=> quote env value to fix syntax error on multiline env

api/account.go, api/apps.go, api/client.go, commands/action_warpper.go, commands/app.go, commands/info_action.go, commands/switch_action.go
命令行工具切换到使用 client center 提供的接口。
- 除了更改请求的地址之外，就是将两步验证部分删掉了（原有的接口在新的 client center 中已经不支持），改为仅在登录时判断是否需要两步验证、如果需要再带上 code 重新请求登录接口。
- 已经在本地 build 之后测试了所有[子命令](https://docs.leancloud.cn/sdk/engine/cli/#%E5%91%BD%E4%BB%A4%E4%BB%8B%E7%BB%8D)，没有问题。
剩下一个有点纠结的点是，如果用户升级新版，原有的存在本地的 XSRF-TOKEN 会用不了（header 里不再带上），部分请求会报错 `[ERROR] unauthorized`。用户重新登录就好了，但这个提示不太友好（这里没有兼容 uluru 的 XSRF-TOKEN 是因为命令行工具的 cookie 过期时间太长了，之后 uluru 彻底不用，还是要报错、要改，不如现在就 👋）。
在 cd77bc9 试了删掉 uluru cookie，这里我能 panic 一下吗（或者你们看怎么改更合适。
=> :alien: switch to client center api

commands/preview_action.go, packaging/deb/control-x64, packaging/deb/control-x86, packaging/msi/lean-cli-x64.wxs, packaging/msi/lean-cli-x86.wxs, packaging/msi/tds-cli-x64.wxs, packaging/msi/tds-cli-x86.wxs, version/version.go
GitHub 这太坑了……先是 GITHUB_SHA 指向的是 PR 要合并到的 commit，而不是 PR 最新的 commit（在 push 等其他事件中却指向的是要 push 的 commit）；再是 GITHUB_REF 在创建 PR 的时候是对的，但合并 PR 的时候就不对了……文档中只字未提，只有遇到了才能发现……
=> Fix GITHUB_REF is wrong for jobs triggered with closed PRs
